-- Espelho versionado da primeira migration remota.
-- A migration já foi aplicada ao projeto Supabase de homologação.
-- Use este arquivo como referência para desenvolvimento local e futuras revisões.

create type public.user_role as enum ('ADMIN','COORDINATOR','APPLICATOR');
create type public.application_status as enum ('NOT_STARTED','IN_PROGRESS','FINALIZED','REOPENED','INCONSISTENT');
create type public.student_presence as enum ('PRESENT','ABSENT');
create type public.race_declaration as enum ('PRETO','PARDO','AMARELO','INDIGENA','BRANCO');
create type public.subject_area as enum ('PORTUGUESE','MATHEMATICS');

create table public.users (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  job_title varchar(160),
  username varchar(80) not null unique,
  password_hash varchar(255) not null,
  role public.user_role not null,
  is_active_user boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.schools (
  id bigint generated by default as identity primary key,
  name varchar(200) not null unique,
  external_code varchar(80),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.evaluations (
  id bigint generated by default as identity primary key,
  name varchar(180) not null,
  school_year integer not null check (school_year between 2000 and 2200),
  edition varchar(50),
  starts_on date,
  ends_on date,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.classes (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete restrict,
  evaluation_id bigint not null references public.evaluations(id) on delete cascade,
  grade smallint not null check (grade between 2 and 9),
  name varchar(120) not null,
  access_code varchar(32) not null unique,
  created_at timestamptz not null default now(),
  unique(evaluation_id, school_id, grade, name)
);

create table public.students (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  external_id varchar(100),
  name varchar(220) not null,
  created_at timestamptz not null default now(),
  unique(class_id, external_id)
);

create table public.tests (
  id bigint generated by default as identity primary key,
  evaluation_id bigint not null references public.evaluations(id) on delete cascade,
  grade smallint not null check (grade between 2 and 9),
  subject public.subject_area not null,
  title varchar(180) not null,
  created_at timestamptz not null default now(),
  unique(evaluation_id, grade, subject)
);

create table public.skills (
  id bigint generated by default as identity primary key,
  code varchar(80) not null,
  description text,
  subject public.subject_area not null,
  grade smallint not null check (grade between 2 and 9),
  unique(code, grade, subject)
);

create table public.questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.tests(id) on delete cascade,
  number integer not null check (number > 0),
  skill_id bigint references public.skills(id) on delete restrict,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  unique(test_id, number)
);

create table public.class_applications (
  id bigint generated by default as identity primary key,
  class_id bigint not null unique references public.classes(id) on delete cascade,
  applicator_id bigint references public.users(id) on delete restrict,
  status public.application_status not null default 'NOT_STARTED',
  started_at timestamptz,
  finalized_at timestamptz,
  reopened_at timestamptz,
  finalized_by bigint references public.users(id) on delete restrict,
  reopened_by bigint references public.users(id) on delete restrict,
  receipt_code varchar(64) unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.student_records (
  id bigint generated by default as identity primary key,
  class_application_id bigint not null references public.class_applications(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  presence public.student_presence not null,
  self_declaration public.race_declaration,
  saved_by bigint not null references public.users(id) on delete restrict,
  saved_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(class_application_id, student_id)
);

create table public.answers (
  id bigint generated by default as identity primary key,
  student_record_id bigint not null references public.student_records(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_option char(1) check (selected_option in ('A','B','C','D') or selected_option is null),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_record_id, question_id)
);

create table public.discursive_uploads (
  id bigint generated by default as identity primary key,
  student_record_id bigint not null unique references public.student_records(id) on delete cascade,
  storage_provider varchar(40) not null default 'GOOGLE_DRIVE',
  storage_file_id varchar(255) not null,
  storage_folder_id varchar(255),
  original_filename varchar(255),
  stored_filename varchar(255) not null,
  mime_type varchar(120),
  file_size_bytes bigint,
  uploaded_by bigint not null references public.users(id) on delete restrict,
  uploaded_at timestamptz not null default now()
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id varchar(120),
  metadata jsonb not null default '{}'::jsonb,
  ip_hash varchar(128),
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.schools enable row level security;
alter table public.evaluations enable row level security;
alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.tests enable row level security;
alter table public.skills enable row level security;
alter table public.questions enable row level security;
alter table public.class_applications enable row level security;
alter table public.student_records enable row level security;
alter table public.answers enable row level security;
alter table public.discursive_uploads enable row level security;
alter table public.audit_logs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
